// All user-facing copy lives here so a Malayalam translation is a swap, not a rewrite.
// Do not hardcode English text directly in JSX — import from `t` instead.

export const t = {
  appName: "Aluminium World",
  tagline: "Every job, in one place.",

  nav: {
    dashboard: "Dashboard",
    enquiries: "Enquiries",
    quotes: "Quotes",
    approvals: "Approvals",
    jobs: "Jobs",
    customers: "Customers",
    vendors: "Vendors",
    rates: "Rate card",
    settings: "Settings",
  },

  login: {
    title: "Who's working today?",
    subtitle: "Demo login — tap your name to continue",
    demoTag: "DEMO MODE",
  },

  roles: {
    owner: "Owner",
    supervisor: "Supervisor",
    workshop: "Workshop",
  },

  enquiry: {
    title: "New enquiry",
    subtitle: "Log the call before the site visit",
    customerName: "Customer name",
    customerMobile: "Mobile number",
    source: "How did they reach us?",
    roughNeed: "What do they need? (rough note)",
    assignTo: "Assign to supervisor",
    save: "Save enquiry",
    listTitle: "Enquiries",
    empty: "No enquiries yet.",
    startSiteVisit: "Start site visit",
    statusNew: "New",
    statusAssigned: "Assigned",
    statusScheduled: "Site visit scheduled",
    statusConverted: "Converted to quote",
  },

  wizard: {
    step1Title: "Where",
    step1Subtitle: "Capture the site location",
    useGps: "Use my current location",
    locating: "Locating…",
    siteLabel: "Site name",
    siteLabelPlaceholder: "e.g. Meethal house, Meppadi",
    capturedAddress: "Captured address",
    next: "Next",

    step2Title: "Who",
    step2Subtitle: "Find or add the customer",
    searchCustomer: "Search by name or phone",
    addNewCustomer: "+ Add new customer",
    customerNamePlaceholder: "Customer name",
    customerMobilePlaceholder: "10-digit mobile number",
    customerAddressPlaceholder: "Address (optional)",

    step3Title: "Items",
    step3Subtitle: "Add each opening to be quoted",
    addItem: "+ Add item",
    itemType: "Item type",
    openingType: "Opening type",
    locationInHouse: "Location in house",
    widthMm: "Width (mm)",
    heightMm: "Height (mm)",
    quantity: "Quantity",
    systemSeries: "System / series",
    glassSpec: "Glass spec",
    finish: "Finish",
    hardware: "Hardware",
    mesh: "Mosquito mesh",
    rate: "Rate (₹/sqft)",
    rateHint: (rate: string, customer: string, date: string) =>
      `Last quoted ₹${rate}/sqft — ${customer}, ${date}`,
    area: "Area",
    minimumApplied: "Minimum billable area applied",
    photos: "Photos",
    addPhoto: "+ Add photo",
    remarks: "Remarks",
    removeItem: "Remove",

    step4Title: "Review & submit",
    step4Subtitle: "Check the numbers before sending",
    subtotal: "Subtotal",
    discount: "Discount",
    gst: "GST",
    total: "Grand total",
    advancePct: "Advance %",
    advanceAmount: "Advance amount",
    leadTime: "Lead time (days)",
    terms: "Terms",
    submit: "Submit quote",
    submitting: "Generating quote…",
  },

  quote: {
    new: "New quote",
    number: "Quote no.",
    status: {
      draft: "Draft",
      pending_approval: "Pending approval",
      approved: "Approved",
      rejected: "Rejected",
      sent: "Sent to customer",
      accepted: "Accepted",
    },
    createdSuccess: (quoteNo: string) => `Quote ${quoteNo} generated`,
    sendToOwner: "Sent to Arif for approval",
  },

  approvals: {
    title: "Approvals",
    subtitle: "Quotes waiting on your decision",
    empty: "Nothing waiting on you. Nice.",
    approve: "Approve",
    approveEdit: "Approve with edit",
    reject: "Reject with reason",
    rejectReasonPlaceholder: "Why is this being sent back?",
    marginFlag: "Below rate card floor",
    approvalMode: "Approval mode",
    modeAlways: "Always — every quote waits for me",
    modeThreshold: "Threshold — only large or discounted quotes wait",
    modeNever: "Never — auto-approve, notify me only",
    thresholdAmount: "Approval needed above (₹)",
  },

  publicQuote: {
    title: "Your quotation",
    from: "From Aluminium World",
    accept: "Accept quotation",
    accepted: "Accepted — thank you!",
    advanceDue: "Advance due to begin work",
    validUntil: "Valid until",
    callUs: "Call us",
    whatsappUs: "WhatsApp us",
    scanToOpen: "Scan to open on your phone",
  },

  tracker: {
    title: "Your job",
    promisedDelivery: "Promised delivery",
    paid: "Paid",
    balance: "Balance due",
    callUs: "Call us",
    stageBlocked: "Waiting",
  },

  jobStages: {
    advance_received: "Advance received",
    material_procurement: "Material procurement",
    cutting: "Cutting",
    fitting: "Fitting / assembly",
    powder_coating: "Powder coating",
    glazing: "Glazing",
    quality_check: "Quality check",
    ready_for_delivery: "Ready for delivery",
    out_for_delivery: "Out for delivery",
    delivered: "Delivered",
    installed: "Installed",
    closed: "Balance settled / closed",
  },

  blockedReasons: {
    awaiting_payment: "Awaiting payment",
    material_unavailable: "Material unavailable",
    vendor_delay: "Vendor delay",
    labour_shortage: "Labour shortage",
    customer_hold: "Customer hold",
    site_not_ready: "Site not ready",
    other: "Other",
  },

  dashboard: {
    title: "Dashboard",
    thisWeek: "This week",
    thisMonth: "This month",
    jobsActive: "Jobs active",
    completed: "Completed",
    pending: "Pending",
    blocked: "Blocked",
    collected: "Collected this month",
    outstanding: "Outstanding",
    awaitingApproval: "Quotes awaiting my approval",
    needsAttention: "Needs your attention",
    allJobs: "All jobs",
    noAttentionItems: "Nothing needs your attention right now.",
  },

  delivery: {
    dispatch: "Dispatch",
    driverMobile: "Driver's mobile number",
    driverName: "Driver's name",
    sendToDriver: "Send delivery link on WhatsApp",
    markDelivered: "Mark delivered",
    delivered: "Delivered",
  },

  vendors: {
    title: "Vendor book",
    subtitle: "Everyone you buy from",
    search: "Search company, person, product, category",
    addVendor: "+ Add vendor",
    call: "Call",
    whatsapp: "WhatsApp",
  },

  common: {
    save: "Save",
    cancel: "Cancel",
    back: "Back",
    loading: "Loading…",
    error: "Something went wrong.",
    notConfigured: "Not connected to a database yet — showing demo data.",
    logout: "Log out",
  },
} as const;
